sudo: required
services:
  - docker

before_install:
  - docker build -t mathesharvadze/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mathesharvadze/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-eu-west-3-809402848040"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
